
[env]
TERM = "xterm-256color"
# font
[font]
size = 12

[font.bold]
family = "JetBrains Mono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono Nerd Font"

[font.normal]
family = "JetBrains Mono Nerd Font"

[font.offset]
x = 0
y = 0

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
# decorations = "none"

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
